### ISSUE TITLE
Could not compile `bitflags`

### ISSUE THREAD

**Issue by JoshuaCrewe** [FraGag/feeds-to-pocket#1]
Hi,

Was looking to check this project out. I get a build error when trying to install with cargo. Any Idea how to resolve this issue?

`macOS version 10.11.6`

```
 $ cargo --version 
    cargo 0.20.0 (a60d185c8 2017-07-13)
```

```
$ cargo install feeds-to-pocket
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing feeds-to-pocket v0.1.5
   Compiling lazy_static v0.2.11
   Compiling safemem v0.2.0
   Compiling httparse v1.2.4
   Compiling version_check v0.1.3
   Compiling unicode-width v0.1.4
   Compiling matches v0.1.6
   Compiling strsim v0.6.0
   Compiling rustc-demangle v0.1.5
   Compiling byteorder v1.2.1
   Compiling slab v0.4.0
   Compiling bitflags v1.0.1
   Compiling serde v1.0.27
error: expected ident, found #
   --> /Users/Joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/lib.rs:423:29
    |
423 |                               #[allow(deprecated)]
    |                               ^
    |
   ::: /Users/Joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/example_generated.rs
    |
4   | / bitflags! {
5   | |     /// This is the same `Flags` struct defined in the [crate level example](../index.html#example).
6   | |     /// Note that this struct is just for documentation purposes only, it must not be used outside
7   | |     /// this crate.
...   |
13  | |     }
14  | | }
    | |_- in this macro invocation

error: Could not compile `bitflags`.
Build failed, waiting for other jobs to finish...
error: failed to compile `feeds-to-pocket v0.1.5`, intermediate artifacts can be found at `/var/folders/dr/x3dscnqj3zj8kpyydf2cszhw0000gn/T/cargo-install.3TkOv4rYfJhF`

Caused by:
  build failed
```

**Comment by FraGag** [comment]
Hey Joshua,

I've been able to reproduce your issue on Linux with Rust 1.19.0 <sup>1</sup>, but not with Rust 1.23.0, which is the latest stable version currently; the program compiles fine with 1.23.0. Could you try updating Rust and Cargo (if you installed them via rustup, then running `rustup update` should do the trick) then installing feeds-to-pocket again?

----

<sup>1</sup> I figured out the Rust version from the Cargo version you posted. In general, for compiler errors, the version of the Rust compiler is more relevant. You can print the compiler's version on a terminal with

```
rustc --version
```

**Comment by JoshuaCrewe** [comment]
huh. Thats strange.
```
rustc --version
rustc 1.23.0
```
is what I get. I first thought it would be a version issue so I updated rust with homebrew to see if that would fix it.

Something must have got out of whack in the time between installing rust and using it here. Brew didn't update all the things as I expected. Aaaaanyway running `rustup update` fixed it for me.

Nice easy one for the start of the week thanks!
