### ISSUE TITLE
Feature idea: Delete / Remove a feed

### ISSUE THREAD

**Issue by JoshuaCrewe** [FraGag/feeds-to-pocket#2]
I have been using this for a little while now and I think you have done a great job 👍 Thanks for building the thing I need.

There have been a few times that I have needed to remove a feed from my list. Either a broken link or I am no longer interested in that blog.

Would it be a good idea to include an additional command to remove a feed ?

**Comment by FraGag** [comment]
I've just released 0.1.6 which implements this feature.

**Comment by JoshuaCrewe** [comment]
Flipping heck that was fast work. Thanks very much 👍
