### ISSUE TITLE
Can't login to pocket

### ISSUE THREAD

**Issue by michelgrolet** [FraGag/feeds-to-pocket#7]
I get the error "The link you followed here is no longer working" on pocket after running `feeds-to-pocket ~/feeds-to-pocket.yaml login`

**Comment by giokeyboard** [comment]
I get the same issue, but this still allows me to run the app and fetch the RSS feeds.

My guess is that there is something going on with the `redirect_uri` param [when sending the request](https://github.com/FraGag/feeds-to-pocket/blob/5681bbecf590d6108a028375610b250f626b9d9f/src/pocket.rs#L184).
From what I can see from the source code, there are some encoded characters and it might break the redirection process maybe?

**Comment by FraGag** [comment]
I guess Pocket simply rejects `data:` URIs in `redirect_uri` now. They used to work in the past.

I'm thinking of replacing the `data:` URI with a link to a static web page served with GitHub Pages from this repo. The target of the redirect doesn't receive the access token or anything like that so there's no chance that credentials could be leaked through this redirect.
